name: ets_api_clients
description: API clients to help process calls from any application that need to access 
version: 1.1.4
homepage: https://clubapplets.ca/
repository: https://github.com/ApplETS/ETS-API-Clients
issue_tracker: https://github.com/ApplETS/ETS-API-Clients/issues
documentation: https://github.com/ApplETS/ETS-API-Clients

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  xml: ^6.4.2
  http: any
  intl: ^0.18.1
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.24.2
  mockito: ^5.4.2
  build_runner: ^2.4.6