name: ets_api_clients
description: API clients to help process calls from any application that need to access 
version: 0.4.2
homepage: https://clubapplets.ca/
repository: https://github.com/ApplETS/ETS-API-Clients
issue_tracker: https://github.com/ApplETS/ETS-API-Clients/issues
documentation: https://github.com/ApplETS/ETS-API-Clients

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^6.0.1
  http: ^0.13.0
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.2
  mockito: ^5.1.0
  build_runner: ^2.1.8