// Mocks generated by Mockito 5.1.0 from annotations
// in ets_api_clients/src/testing/mon_ets_api_mock.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:ets_api_clients/src/models/mon_ets_user.dart' as _i2;
import 'package:ets_api_clients/src/monets_api_client_implementation.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMonETSUser_0 extends _i1.Fake implements _i2.MonETSUser {}

/// A class which mocks [MonETSAPIClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMonETSAPIClient extends _i1.Mock implements _i3.MonETSAPIClient {
  MockMonETSAPIClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MonETSUser> authenticate(
          {String? username, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#authenticate, [],
                  {#username: username, #password: password}),
              returnValue: Future<_i2.MonETSUser>.value(_FakeMonETSUser_0()))
          as _i4.Future<_i2.MonETSUser>);
}
