// Mocks generated by Mockito 5.1.0 from annotations
// in ets_api_clients/src/testing/signets_api_mock.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:ets_api_clients/src/models/course.dart' as _i8;
import 'package:ets_api_clients/src/models/course_activity.dart' as _i6;
import 'package:ets_api_clients/src/models/course_review.dart' as _i11;
import 'package:ets_api_clients/src/models/course_summary.dart' as _i2;
import 'package:ets_api_clients/src/models/profile_student.dart' as _i3;
import 'package:ets_api_clients/src/models/program.dart' as _i10;
import 'package:ets_api_clients/src/models/schedule_activity.dart' as _i7;
import 'package:ets_api_clients/src/models/session.dart' as _i9;
import 'package:ets_api_clients/src/signets_api_client_implementation.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCourseSummary_0 extends _i1.Fake implements _i2.CourseSummary {}

class _FakeProfileStudent_1 extends _i1.Fake implements _i3.ProfileStudent {}

/// A class which mocks [SignetsAPIClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignetsAPIClient extends _i1.Mock implements _i4.SignetsAPIClient {
  MockSignetsAPIClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> authenticate({String? username, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #authenticate, [], {#username: username, #password: password}),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<List<_i6.CourseActivity>> getCoursesActivities(
          {String? username,
          String? password,
          String? session = r'',
          String? courseGroup = r'',
          DateTime? startDate,
          DateTime? endDate}) =>
      (super.noSuchMethod(
          Invocation.method(#getCoursesActivities, [], {
            #username: username,
            #password: password,
            #session: session,
            #courseGroup: courseGroup,
            #startDate: startDate,
            #endDate: endDate
          }),
          returnValue: Future<List<_i6.CourseActivity>>.value(
              <_i6.CourseActivity>[])) as _i5.Future<List<_i6.CourseActivity>>);
  @override
  _i5.Future<List<_i7.ScheduleActivity>> getScheduleActivities(
          {String? username, String? password, String? session = r''}) =>
      (super.noSuchMethod(
              Invocation.method(#getScheduleActivities, [], {
                #username: username,
                #password: password,
                #session: session
              }),
              returnValue: Future<List<_i7.ScheduleActivity>>.value(
                  <_i7.ScheduleActivity>[]))
          as _i5.Future<List<_i7.ScheduleActivity>>);
  @override
  _i5.Future<List<_i8.Course>> getCourses(
          {String? username, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getCourses, [], {#username: username, #password: password}),
              returnValue: Future<List<_i8.Course>>.value(<_i8.Course>[]))
          as _i5.Future<List<_i8.Course>>);
  @override
  _i5.Future<_i2.CourseSummary> getCourseSummary(
          {String? username, String? password, _i8.Course? course}) =>
      (super.noSuchMethod(
              Invocation.method(#getCourseSummary, [],
                  {#username: username, #password: password, #course: course}),
              returnValue:
                  Future<_i2.CourseSummary>.value(_FakeCourseSummary_0()))
          as _i5.Future<_i2.CourseSummary>);
  @override
  _i5.Future<List<_i9.Session>> getSessions(
          {String? username, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getSessions, [], {#username: username, #password: password}),
              returnValue: Future<List<_i9.Session>>.value(<_i9.Session>[]))
          as _i5.Future<List<_i9.Session>>);
  @override
  _i5.Future<_i3.ProfileStudent> getStudentInfo(
          {String? username, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getStudentInfo, [], {#username: username, #password: password}),
          returnValue:
              Future<_i3.ProfileStudent>.value(_FakeProfileStudent_1())) as _i5
          .Future<_i3.ProfileStudent>);
  @override
  _i5.Future<List<_i10.Program>> getPrograms(
          {String? username, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getPrograms, [], {#username: username, #password: password}),
              returnValue: Future<List<_i10.Program>>.value(<_i10.Program>[]))
          as _i5.Future<List<_i10.Program>>);
  @override
  _i5.Future<List<_i11.CourseReview>> getCourseReviews(
          {String? username, String? password, _i9.Session? session}) =>
      (super.noSuchMethod(
              Invocation.method(#getCourseReviews, [], {
                #username: username,
                #password: password,
                #session: session
              }),
              returnValue:
                  Future<List<_i11.CourseReview>>.value(<_i11.CourseReview>[]))
          as _i5.Future<List<_i11.CourseReview>>);
}
